version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root --with docs

python:
  version: 3.9

sphinx:
  configuration: docs/conf.py
