version: 2

build:
  jobs:
    install:
      - bash -c "curl -sSL https://install.python-poetry.org | python3 - && export PATH=\"$HOME/.local/bin:$PATH\" && poetry install --no-root --with docs"

sphinx:
  configuration: docs/source/conf.py
