version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
    - pip install -U poetry
    - poetry config virtualenvs.create false --local
    - poetry install --no-root --with docs

sphinx:
  configuration: docs/conf.py
