version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - curl -sSL https://install.python-poetry.org | python3 -
    install:
      - poetry install --no-root --with docs

python:
  install:
    - method: poetry
      extras: []
      with: [docs]

sphinx:
  configuration: docs/conf.py
