version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-root --with docs
    - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html
    
sphinx:
  configuration: docs/conf.py
