version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    install:
      - pip install virtualenv
      - >
        curl -sSL https://install.python-poetry.org | python3 - && \
        export PATH="$HOME/.local/bin:$PATH" && \
        poetry install --no-root --with docs

sphinx:
  configuration: docs/conf.py
